[package]
name = "noiseexplorer_nx"
version = "1.0.2"
authors = ["Symbolic Software <georgio@symbolic.software>"]
edition = "2018"

[dependencies]
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.3"
hacl-star = "0.1.0"
hex = "0.3.2"
rand = "0.6.5"
zeroize = "0.9.1"
