[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "1.1.0", features = ["full"] }

[[example]]
name = "setup_connection"
path = "setup_connection.rs"

